# Phase 1 Postgres 现场演示（apply → 样例查询 → 整体验收）

## 你是不是要找「数据库 + 静态查询」演示？

**是的，本笔记本就是这个意思**，在工程上具体是：

1. **数据库**：真实的 **PostgreSQL**，里面已经（或即将）执行 `db/phase1` 的 **DDL + seed**；**§0.5** 对照 [`TABLES_LANDED.md`](../../db/phase1/TABLES_LANDED.md) 看表是否在库里、**行数**多少——用来讲「库结构落地 + 演示数据在库里」。
2. **静态查询**：仓库里的 **`sql/queries/p0/*.sql`** 即 Phase 1 P0 查询；**§1** 用 Python 连库对这些 SQL 做 **`SELECT`**，把结果用表格（+ 纯文本备份）展示；**§2** 用同一批 SQL 做整批断言（和 CI 思路一致）。

**不是**：不接 Postgres 的「零配置动画」、也不是仓库里别的内存 smoke；**没有连上库就不会有表可看**，不是渲染坏了。

**为什么你容易感觉「始终没有效果」**：下面任一没满足时，代码会 **跳过** 或只打一行字，看起来像「什么都没发生」——最常见是 **「连接串」格没在本 kernel 里真正赋值**（终端 `export` 对 notebook 常常无效），或 **没对 DSN 指向的库跑 apply**、或 **psycopg[binary] / 内核选错**。请按顺序：**连接串格 → 自检为「是」→（建议）§0 apply →§0.5 →§1**。

---

面向**对人讲解**：对照 [`db/phase1/TABLES_LANDED.md`](../../db/phase1/TABLES_LANDED.md) 的核心表，看 **`sql/queries/p0`** 在 seed 数据上**查到了什么**（表格），再跑与终端相同的整批验收。

| 笔记本 | 侧重 |
|--------|------|
| **`phase1_database_checks.ipynb`** | 与 CI 对齐的验收（`verify_seed_counts` + `run_p0_queries`），输出以返回码为主。 |
| **本笔记本** | 可选 `apply`、**0.5 库表+行数**、**§1 多条 P0 查询 DataFrame**、子进程跑 `run_p0_queries`（输出落在格内）、`phase1_acceptance --strict`（有 DSN 才跑）。 |

**前置**
- 环境变量 **`EGM_PG_DSN`**：见下面 **「连接串 EGM_PG_DSN」** 代码格（在 notebook 里赋值即可，不必依赖终端 export）。
- 当前 Jupyter **kernel 所用的 Python 环境**里安装 **`psycopg[binary]`**（与只装 `psycopg` 不同）：
  - 终端：`pip install 'psycopg[binary]>=3.2'`（建议在与 notebook 相同的 venv 里执行，例如仓库下 `.venv`）。
  - 若仍报 `no pq wrapper` / `libpq library not found`：在 macOS 可 `brew install libpq`，或确认 Jupyter 内核选的是已装 `[binary]` 的那个解释器；改完后 **Restart Kernel** 再跑。
- 跑下面「0. apply」格需要 **`psql`** 在 `PATH` 里。
- **`pandas`**：项目 `pyproject.toml` 已列为依赖；若 kernel 里没有请 `pip install pandas`。
- 在仓库内打开本 notebook（或 cwd 能向上找到含 `src/egm` 的根目录）。

---

> **重要**：本演示连接的是**真实 PostgreSQL**。未在「连接串」格设置 `EGM_PG_DSN` 时，后面只会出现「跳过 / 返回码 0 但不跑库」——**不会出现表、行数或查询结果**；这不是 bug。设置 DSN 后请先跑 **「自检」** 格确认显示「是」，再跑 **0.5** 与 **§1**；§1 中每个查询除 DataFrame 外还有 **纯文本表**，在 Cursor 里即使富文本不渲染也能看到数据。

In [1]:
import importlib.util
import sys
from pathlib import Path


def find_repo_root() -> Path:
    for p in [Path.cwd(), *Path.cwd().parents]:
        if (p / "src" / "egm").exists():
            return p
    raise RuntimeError("找不到仓库根（含 src/egm）。请在仓库内打开 notebook 或 cd 到仓库。")


REPO = find_repo_root()
SRC = REPO / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))
print("REPO:", REPO)

REPO: /Users/ousiachai/dev/errorgnomark_dev

## 连接串 `EGM_PG_DSN`

Jupyter kernel **不会自动继承**你在另一个终端里 `export` 的变量（除非用**同一个**已 export 的 shell 启动 Jupyter）。请在**下一格 Python 代码**里取消注释并填写 `os.environ["EGM_PG_DSN"] = ...`，运行该格后再跑后面的 apply / 查询 / 验收。

（若你已在启动 Jupyter 的 shell 里 export 过，下一格可保持注释，直接运行下一格确认是否已可见。）

In [2]:
import os

# ▼▼ 在下面这一行**去掉行首 #**，把 USER / PASS / 主机 / 库名 改成你的 Postgres，然后运行本格 ▼▼
os.environ["EGM_PG_DSN"] = "postgresql://ousiachai:789523@127.0.0.1:5432/egm_phase1"# 与终端里 export 的写法相同，例如：postgresql://postgres:你的密码@localhost:5432/egm_phase1

if os.environ.get("EGM_PG_DSN"):
    print("EGM_PG_DSN: 已设置（本 kernel 内可见）")
else:
    print("EGM_PG_DSN: 未设置 — 请取消上一行注释并填写后，再运行本格。")

EGM_PG_DSN: 已设置（本 kernel 内可见）

In [3]:
# --- 自检：只有这里显示「是」，后面的 0.5 / §1 才会出表格（在「连接串」格赋值后务必先跑本格）---
import os

_ok = bool(os.environ.get("EGM_PG_DSN"))
print("当前 Jupyter kernel 内 EGM_PG_DSN 已设置:", "是" if _ok else "否")
if _ok:
    s = os.environ["EGM_PG_DSN"]
    print("连接串前缀（便于确认连的是哪个库，不含密码）:", repr(s[:40]))
else:
    print("提示：在终端 export 对 notebook 常常无效；请在上一格用 os.environ['EGM_PG_DSN']=... 赋值并运行，再运行本格。")

当前 Jupyter kernel 内 EGM_PG_DSN 已设置: 是
连接串前缀（便于确认连的是哪个库，不含密码）: 'postgresql://ousiachai:789523@127.0.0.1:'

## 0.（可选）`apply_phase1.sh`

对 **`EGM_PG_DSN`** 指向的库执行 `001_schema.sql` + `seed/010`～`040`。**非空库可能因主键冲突失败**；开发环境可先删库/删 schema 再跑。

**若本格输出「PATH 中未找到 psql」**：说明 Jupyter 进程里找不到 `psql` 命令。任选其一：① 安装并把 `psql` 加入 PATH（macOS 常见：`brew install libpq`，再按 `brew info libpq` 把 `bin` 加到 PATH）；② **在终端**（能跑 `psql` 的 shell）里 `export EGM_PG_DSN=...` 后执行 `./scripts/postgres/apply_phase1.sh`，与 notebook 里 DSN 指向同一库即可。

**若后面出现 `connection refused` / 连不上 127.0.0.1:5432`**：说明 **Postgres 服务没在监听**（或端口不是 5432）。请先在本机**启动 Postgres**（或把 DSN 里的主机/端口改成你实际运行的实例），再用 `psql "$EGM_PG_DSN" -c 'select 1'` 在终端试通后再跑 notebook。

若你已在终端跑过 apply，可**跳过**本格。

In [4]:
import os
import shutil
import subprocess
import sys

dsn = os.environ.get("EGM_PG_DSN")
if not dsn:
    print("跳过：未设置 EGM_PG_DSN")
elif not shutil.which("psql"):
    print("跳过：PATH 中未找到 psql")
else:
    script = REPO / "scripts/postgres/apply_phase1.sh"
    p = subprocess.run(
        ["bash", str(script)],
        cwd=str(REPO),
        env={**os.environ},
        capture_output=True,
        text=True,
    )
    if p.stdout:
        print(p.stdout, end="")
    if p.stderr:
        print(p.stderr, end="", file=sys.stderr)
    print("exit code:", p.returncode)
    p.check_returncode()

跳过：PATH 中未找到 psql

## 0.5 数据库一览（与 `TABLES_LANDED.md` 对齐）

在**已设置 `EGM_PG_DSN`** 的前提下：检查这些表是否在 `public` schema 中存在，并统计**行数**（apply + seed 之后应多为正数）。用于对外说明「库结构落地 + 演示数据在库里」。

In [5]:
import os

import pandas as pd
from IPython.display import display
from psycopg import Connection, sql
from psycopg.rows import dict_row

# 与 db/phase1/TABLES_LANDED.md 中「表名」列一致（维护时请两边对齐）
TABLES_LANDED = [
    "chip",
    "qubit",
    "coupler",
    "coupler_endpoint",
    "scope",
    "scope_member",
    "source",
    "version",
    "metric_definition",
    "structure_event",
    "calibration_run",
    "calibration_artifact",
    "benchmark_run",
    "observation_record",
    "structure_snapshot",
    "calibration_snapshot",
    "system_state",
    "lineage",
    "lineage_edge",
]

dsn = os.environ.get("EGM_PG_DSN")
if not dsn:
    print("已跳过：未设置 EGM_PG_DSN — 无法展示「数据库里有谁」。")
else:
    rows_out = []
    with Connection.connect(dsn, row_factory=dict_row) as conn:
        with conn.cursor() as cur:
            for t in TABLES_LANDED:
                cur.execute(
                    """
                    SELECT EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = %(name)s
                    ) AS exists
                    """,
                    {"name": t},
                )
                exists = bool(cur.fetchone()["exists"])
                n = None
                if exists:
                    q = sql.SQL("SELECT count(*)::bigint AS c FROM {}").format(sql.Identifier(t))
                    cur.execute(q)
                    n = int(cur.fetchone()["c"])
                rows_out.append({"table": t, "exists_in_db": exists, "row_count": n})
    df_sum = pd.DataFrame(rows_out)
    display(df_sum)
    print("\n[TABLES_LANDED — 文本备份，不依赖富文本渲染]\n")
    with pd.option_context("display.max_columns", 12, "display.width", 100):
        print(df_sum.to_string(index=False))
    print()

                   table  exists_in_db  row_count
0                   chip          True          2
1                  qubit          True          8
2                coupler          True          6
3       coupler_endpoint          True         12
4                  scope          True          4
5           scope_member          True          0
6                 source          True          1
7                version          True          0
8      metric_definition          True          1
9        structure_event          True          0
10       calibration_run          True          0
11  calibration_artifact          True          0
12         benchmark_run          True          0
13    observation_record          True          0
14    structure_snapshot          True          0
15  calibration_snapshot          True          0
16          system_state          True          0
17               lineage          True          0
18          lineage_edge          True          0

[TABLES_LANDED — 文本备份，不依赖富文本渲染]

               table  exists_in_db  row_count
                chip          True          2
               qubit          True          8
             coupler          True          6
    coupler_endpoint          True         12
               scope          True          4
        scope_member          True          0
              source          True          1
             version          True          0
   metric_definition          True          1
     structure_event          True          0
     calibration_run          True          0
calibration_artifact          True          0
       benchmark_run          True          0
  observation_record          True          0
  structure_snapshot          True          0
calibration_snapshot          True          0
        system_state          True          0
             lineage          True          0
        lineage_edge          True          0

## 1. 代表性 `sql/queries/p0`（展示「能查到数据」）

以下与 `run_p0_queries.py` 使用**同一参数风格**，在 `chip-alpha` seed 上执行：**Q1 / Q2 / Q5 / Q12**。每个查询会输出 **HTML 表格（若环境支持）** 以及 **纯文本表（`print`，一定可见）**。

若本格只有「已跳过」两行字、没有任何表：**说明当前 kernel 里没有 `EGM_PG_DSN`**，请先跑「连接串」格 + 上面「自检」格显示为「是」，再单独重跑本格。

In [6]:
import os

import pandas as pd
from IPython.display import Markdown, display

dsn = os.environ.get("EGM_PG_DSN")
if not dsn:
    print(
        "已跳过：本 kernel 内没有 EGM_PG_DSN。\n"
        "请先运行上面「连接串 EGM_PG_DSN」代码格，再运行本格。"
    )
else:
    from egm.datastore.phase1_pg_constants import CHIP_ALPHA_ID
    from psycopg import Connection
    from psycopg.rows import dict_row

    p0 = REPO / "sql" / "queries" / "p0"

    def fetch_demo(name: str, rel_sql: str, params: dict) -> pd.DataFrame:
        sql_text = (p0 / rel_sql).read_text()
        with Connection.connect(dsn, row_factory=dict_row) as conn:
            with conn.cursor() as cur:
                cur.execute(sql_text, params)
                rows = cur.fetchall()
        return pd.DataFrame(rows)

    def show_query(title_md: str, name: str, rel_sql: str, params: dict) -> None:
        display(Markdown(title_md))
        df = fetch_demo(name, rel_sql, params)
        print(f"{name} — {rel_sql} — {len(df)} row(s)")
        display(df)
        sep = "=" * 72
        plain = title_md.replace("### ", "").strip()
        print(f"\n{sep}\n{plain}（文本表）\n{sep}")
        with pd.option_context("display.max_columns", 24, "display.width", 140, "display.max_colwidth", 40):
            print(df.to_string(index=False))
        print()

    print("—— 下面每条：先 Markdown 标题，再 DataFrame，再纯文本表（Cursor 里若看不到 HTML 表，请看 print 段）——\n")
    show_query("### Q1 — 按 id 查芯片", "Q1", "q01_chip_by_id.sql", {"chip_id": CHIP_ALPHA_ID})
    show_query("### Q2 — 芯片上 qubit 列表", "Q2", "q02_list_chip_qubits.sql", {"chip_id": CHIP_ALPHA_ID})
    show_query("### Q5 — 最新 structure_snapshot", "Q5", "q05_structure_snapshot_latest.sql", {"chip_id": CHIP_ALPHA_ID})
    show_query("### Q12 — benchmark_run 历史", "Q12", "q12_benchmark_runs_by_chip.sql", {"chip_id": CHIP_ALPHA_ID})

—— 下面每条：先 Markdown 标题，再 DataFrame，再纯文本表（Cursor 里若看不到 HTML 表，请看 print 段）——

### Q1 — 按 id 查芯片

Q1 — q01_chip_by_id.sql — 1 row(s)

,chip_id,chip_name,generation_name,vendor,status,created_at
0,a0000001-0000-4000-8000-000000000001,chip-alpha,gen-demo,demo,active,2026-05-12 23:20:43.258306+08:00

========================================================================
Q1 — 按 id 查芯片（文本表）
========================================================================
                             chip_id  chip_name generation_name vendor status                       created_at
a0000001-0000-4000-8000-000000000001 chip-alpha        gen-demo   demo active 2026-05-12 23:20:43.258306+08:00

### Q2 — 芯片上 qubit 列表

Q2 — q02_list_chip_qubits.sql — 4 row(s)

,qubit_id,chip_id,qubit_index,qubit_label
0,d0000001-0000-4000-8000-000000010001,a0000001-0000-4000-8000-000000000001,0,alpha-q0
1,d0000001-0000-4000-8000-000000010002,a0000001-0000-4000-8000-000000000001,1,alpha-q1
2,d0000001-0000-4000-8000-000000010003,a0000001-0000-4000-8000-000000000001,2,alpha-q2
3,d0000001-0000-4000-8000-000000010004,a0000001-0000-4000-8000-000000000001,3,alpha-q3

========================================================================
Q2 — 芯片上 qubit 列表（文本表）
========================================================================
                            qubit_id                              chip_id  qubit_index qubit_label
d0000001-0000-4000-8000-000000010001 a0000001-0000-4000-8000-000000000001            0    alpha-q0
d0000001-0000-4000-8000-000000010002 a0000001-0000-4000-8000-000000000001            1    alpha-q1
d0000001-0000-4000-8000-000000010003 a0000001-0000-4000-8000-000000000001            2    alpha-q2
d0000001-0000-4000-8000-000000010004 a0000001-0000-4000-8000-000000000001            3    alpha-q3

### Q5 — 最新 structure_snapshot

Q5 — q05_structure_snapshot_latest.sql — 0 row(s)

Empty DataFrame
Columns: []
Index: []

========================================================================
Q5 — 最新 structure_snapshot（文本表）
========================================================================
Empty DataFrame
Columns: []
Index: []

### Q12 — benchmark_run 历史

Q12 — q12_benchmark_runs_by_chip.sql — 0 row(s)

Empty DataFrame
Columns: []
Index: []

========================================================================
Q12 — benchmark_run 历史（文本表）
========================================================================
Empty DataFrame
Columns: []
Index: []

## 2. 收尾：`run_p0_queries.py`（整批 P0 断言）

与终端 `PYTHONPATH=src python scripts/postgres/run_p0_queries.py` 等价。下面用子进程跑一遍，**标准输出会出现在本格下方**（每条 `qXX: ok (n row(s))`）；无 DSN 时只会看到 skip 提示。

In [7]:
import os
import subprocess
import sys

dsn = os.environ.get("EGM_PG_DSN")
if not dsn:
    print("跳过：未设置 EGM_PG_DSN（与终端脚本行为一致：无连接则不跑断言）。")
else:
    r = subprocess.run(
        [sys.executable, str(REPO / "scripts/postgres/run_p0_queries.py")],
        cwd=str(REPO),
        env={**os.environ, "PYTHONPATH": str(SRC)},
        capture_output=True,
        text=True,
    )
    if r.stdout:
        print(r.stdout, end="")
    if r.stderr:
        print(r.stderr, end="")
    print("---")
    print("run_p0_queries 返回码:", r.returncode)

q01: ok (1 row(s))
q02: ok (4 row(s))
q03: ok (3 row(s))
q04: ok (2 row(s))
q05: expected rows from q05_structure_snapshot_latest.sql, got 0
---
run_p0_queries 返回码: 1

## 3.（可选）`phase1_acceptance --strict`

与 CI 一致：未设置 `EGM_PG_DSN` 或未安装 psycopg 时 **退出码 1**。下面一格在**无 DSN 时会主动跳过**，避免演示时误以为是「库坏了」。

等价终端：`PYTHONPATH=src python -m egm.datastore.phase1_acceptance --strict`（见 `db/phase1/README.md`）。

In [8]:
import os
import subprocess
import sys

if not os.environ.get("EGM_PG_DSN"):
    print("跳过 phase1_acceptance --strict：未设置 EGM_PG_DSN（CI 里会失败；演示时请先配置连接串）。")
else:
    r = subprocess.run(
        [sys.executable, "-m", "egm.datastore.phase1_acceptance", "--strict"],
        cwd=str(REPO),
        env={**os.environ, "PYTHONPATH": str(SRC)},
        capture_output=True,
        text=True,
    )
    if r.stdout:
        print(r.stdout, end="")
    if r.stderr:
        print(r.stderr, end="")
    print("---")
    print("phase1_acceptance --strict 返回码:", r.returncode)

structure_snapshot: expected exactly 2, got 0
---
phase1_acceptance --strict 返回码: 1